### PR TITLE
stm32f429_discovery_no_os: update to v5.2

### PR DESCRIPTION
**Pull request by seyyah**
Update from v5.1.2-beta to v5.2

### CODE REVIEW

**Comment by seyyah** [comment]
I don't have STM32SW4 (Ac6) compiler. We use Atollic TrueStudio IDE.

**Comment by kisvegabor** [comment]
So can you add the Atollic version of `stm32f746_discovery_no_os` as a new project? For example with the name: `stm32f746_discovery_no_os_atollic`

**Comment by seyyah** [comment]
Ok

23 Eki 2018 Sal 09:36 tarihinde Gabor Kiss-Vamosi <notifications@github.com>
şunu yazdı:

**Comment by kisvegabor** [comment]
1. Now the SW4STM32 is with Ac6 as well.
2. It seems the submodules are messed up. I think it would be clearer just to simply add a new directory like `stm32f429_no_os_true_studio`

**Comment by embeddedt** [comment]
@kisvegabor Should I close this PR?

**Comment by kisvegabor** [comment]
As the projects are separated and Atollic project is added too we can close it.

**Pull request closed without merging**
